<!DOCTYPE html>
<html>

<head>

    <title>
        <?=$title; ?> 
    </title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1.0">

<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700,700italic" />
    <link rel="stylesheet" type="text/css" href="/css/styles.css" />

</head>

<body>
    <?php include  __DIR__ . './partials/header.phtml'?>
    <div class="container" id="content">
        <div class="row" id="content-inside">
            <?php include  __DIR__ . './content/'. $contentName . '.phtml'?>
        </div>
    </div>
   <?php include  __DIR__ . './partials/footer.phtml'?>
</body>

</html>
