 <footer>
        <div  class="footer" id="footer">
            <div class="container">
                <p> Copyright © Shalom Medicine. All right reserved. </p>
                <ul class="social">
                    <li> <a href="#"> <i class=" fa fa-facebook">   </i> </a> </li>
                    <li> <a href="#"> <i class="fa fa-twitter">   </i> </a> </li>
                    <li> <a href="#"> <i class="fa fa-google-plus">   </i> </a> </li>
                </ul>
            </div>
        </div>
    </footer>