<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#SBcert-pop" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <div class="collapse navbar-collapse" id="SBcert-pop">
      <ul class="nav navbar-nav pull-right">
        <li><a href="/admin">Admin</a></li>
        <li><a href="/register">Register</a></li>
      </ul>
    </div>
  </div>
</nav>